# GRIDEDGE Startup Database — 100 companies
# GridEdge Score = Market Pull(20) + Tech Moat(20) + Commercial(20) + Scale Risk(15) + Korea Fit(15) + Exit(10)

COMPANIES = [

# ══════════════════════════════════════════
# SECTOR 1: DC Power & BTM (20개)
# ══════════════════════════════════════════
{"id":"emerald-ai","sector":"DC Power & BTM","sub":"Load Flexibility","name":"Emerald AI","country":"USA","founded":2024,"stage":"Seed + Strategic","raised":"$68M","last_round":"$25M Strategic Round (EIP led)","last_date":"Mar 2026","investors":["EIP (lead)","NVentures","Samsung Ventures","GE Vernova","Siemens","Eaton","Lowercarbon","IQT","Radical Ventures","Salesforce Ventures","Amplo","CRV"],"desc":"Makes AI data centers grid-interactive assets. Workload-aware power management.","moat":"Real-time load flex. NVIDIA 96MW pilot. EIP + GE Vernova + Siemens = utility channel.","customers":["NVIDIA (96MW)","Hyperscalers"],"trl":8,"mp":18,"tm":16,"cr":14,"sr":11,"kf":13,"ep":9,"score":81,"korea":["Samsung C&T","SK","KT","Naver"],"acquirer":["Schneider","Eaton","GE Vernova"],"thesis":"Grid-interactive AI DC structurally undervalued. NVIDIA pilot validates commercial.","risk":"Hyperscaler adoption speed. ISO regulatory complexity.","url":"https://www.emeraldai.co"},

{"id":"bloom-energy","sector":"DC Power & BTM","sub":"Fuel Cell","name":"Bloom Energy","country":"USA","founded":2001,"stage":"Public (NYSE: BE)","raised":"Public","last_round":"SK $300M strategic","last_date":"2021","investors":["SK Inc","SoftBank","Kleiner Perkins"],"desc":"Solid oxide fuel cells for on-site AI DC power. Bypasses interconnection queue.","moat":"SOFC proprietary ceramic. 90%+ uptime. Zero-emission with biogas option.","customers":["Samsung","Apple","AT&T","AI DC operators"],"trl":9,"mp":17,"tm":15,"cr":18,"sr":10,"kf":17,"ep":7,"score":84,"korea":["SK Energy","Samsung Electronics","LG","POSCO"],"acquirer":["SK","Doosan","Hanwha"],"thesis":"BTM demand surging as interconnection queue hits 4+ years. SK validates Korea.","risk":"Gas dependency. OBBBA subsidy risk.","url":"https://www.bloomenergy.com"},

{"id":"oklo","sector":"DC Power & BTM","sub":"Microreactor","name":"Oklo","country":"USA","founded":2013,"stage":"Public (NYSE: OKLO)","raised":"Public","last_round":"Sam Altman SPAC","last_date":"2024","investors":["Sam Altman","Founders Fund","Meta (offtake)"],"desc":"Aurora 15MW microreactor. On-site nuclear for AI DC.","moat":"First NRC application submitted. Meta offtake signed. Sam Altman credibility.","customers":["Meta (offtake)","DoD sites"],"trl":5,"mp":16,"tm":14,"cr":5,"sr":18,"kf":8,"ep":8,"score":69,"korea":["KEPCO","KAERI","Doosan"],"acquirer":["Strategic standalone"],"thesis":"AI DC on-site nuclear dream. Meta validation. High risk but massive upside.","risk":"NRC denied once. COD 2027+ best case. $15,000/kW FOAK. HIGH RISK.","url":"https://oklo.com"},

{"id":"terrapower","sector":"DC Power & BTM","sub":"SMR","name":"TerraPower","country":"USA","founded":2006,"stage":"Private","raised":"$1B+","last_round":"SK+NVentures+Gates","last_date":"2022-24","investors":["Bill Gates","SK Inc","NVentures","Berkshire"],"desc":"Natrium 345MW sodium fast reactor + molten salt thermal storage. Wyoming.","moat":"Thermal storage differentiator. Dispatchable nuclear. SK+NVIDIA backing.","customers":["PacifiCorp","Wyoming state"],"trl":6,"mp":14,"tm":17,"cr":6,"sr":15,"kf":11,"ep":7,"score":70,"korea":["SK Inc","KEPCO","Doosan","KAERI"],"acquirer":["Strategic only"],"thesis":"Best-funded SMR. Thermal storage = unique dispatchability. COD 2030.","risk":"$15,000/kW FOAK. Sodium complexity. Long timeline.","url":"https://www.terrapower.com"},

{"id":"kairos-power","sector":"DC Power & BTM","sub":"SMR","name":"Kairos Power","country":"USA","founded":2016,"stage":"Private","raised":"$600M+","last_round":"Google MDA + DOE $303M","last_date":"2024","investors":["Google","DOE","a16z"],"desc":"FHR 140MW pebble-bed fluoride salt reactor. Hermes demo under NRC review.","moat":"Google 500MW MDA. Pebble bed passive safety. Industrial heat option.","customers":["Google (500MW MDA)"],"trl":6,"mp":15,"tm":16,"cr":7,"sr":15,"kf":10,"ep":7,"score":70,"korea":["KEPCO","KAERI","Doosan"],"acquirer":["Strategic only"],"thesis":"Google credibility. Hermes 2027 demo. Most advanced non-LWR SMR.","risk":"Novel coolant regulatory unknown. COD 2030+.","url":"https://kairospower.com"},

{"id":"commonwealth-fusion","sector":"DC Power & BTM","sub":"Fusion","name":"Commonwealth Fusion","country":"USA","founded":2018,"stage":"Series B2","raised":"$2.86B","last_round":"$863M Series B2","last_date":"Aug 2025","investors":["Tiger Global (B lead)","NVentures","Google (PPA+investor)","Breakthrough Energy","Khosla Ventures","Bill Gates","Emerson Collective","Eni","Temasek","Morgan Stanley (Counterpoint Global)"],"desc":"SPARC tokamak fusion. 400MW ARC commercial plant. MIT spinout.","moat":"HTS magnets (REBCO). Google agreed to buy 200MW from ARC.","customers":["Google (200MW agreement)"],"trl":5,"mp":15,"tm":19,"cr":4,"sr":19,"kf":9,"ep":7,"score":73,"korea":["ITER Korea","KAERI","Samsung"],"acquirer":["Strategic 2035+"],"thesis":"If fusion works = game over for all other energy. $863M from NVIDIA/Google = serious.","risk":"TRL 5. Net energy not demonstrated. COD 2035+. WATCH not LEAD.","url":"https://www.cfs.energy"},

{"id":"enchanted-rock","sector":"DC Power & BTM","sub":"Microgrid","name":"Enchanted Rock","country":"USA","founded":2012,"stage":"Series C","raised":"$200M+","last_round":"$150M Series C","last_date":"2024","investors":["Fifth Wall","Verizon Ventures","Chevron Tech"],"desc":"Natural gas microgrids for C&I and AI DC campuses. 99.999% uptime SLA.","moat":"Proven ops. AI DC co-location expertise. Verizon = carrier real estate access.","customers":["Verizon","Kroger","H-E-B"],"trl":9,"mp":15,"tm":13,"cr":16,"sr":9,"kf":11,"ep":8,"score":72,"korea":["SK E&S","GS Energy","Hanwha"],"acquirer":["NextEra","Quanta","Black & Veatch"],"thesis":"C&I microgrid as AI DC BTM bridge. Gas+BESS hybrid. Revenue proven.","risk":"Gas-dependent. Bridge solution as grid improves.","url":"https://enchantedrock.com"},

{"id":"antora-energy","sector":"DC Power & BTM","sub":"Thermal Storage","name":"Antora Energy","country":"USA","founded":2018,"stage":"Series B","raised":"$272M","last_round":"$150M Series B","last_date":"Feb 2024","investors":["Decarbonization Partners (BlackRock+Temasek lead)","Breakthrough Energy Ventures","Lowercarbon Capital","BHP Ventures","Emerson Collective","NextEra Energy Resources","GS Futures","Overture VC"],"desc":"Carbon block thermal batteries. Stores renewable as heat (1500°C). Zero-emission industrial power.","moat":"Thermophotovoltaic conversion. 10-100hr duration. Microsoft pilot.","customers":["Summit Materials (cement)","Calgren Renewable Fuels","Industrial manufacturers"],"trl":7,"mp":14,"tm":17,"cr":10,"sr":13,"kf":12,"ep":8,"score":74,"korea":["POSCO","Hyundai Steel","SK Innovation","Samsung SDI"],"acquirer":["Siemens Energy","GE Vernova","BASF"],"thesis":"Industrial decarbonization + AI DC thermal. Microsoft = strongest possible pilot.","risk":"TRL 7 — pre-commercial scale. Manufacturing challenge.","url":"https://antoraenergy.com"},

{"id":"ampd-energy","sector":"DC Power & BTM","sub":"Construction Power","name":"AMPD Energy","country":"Hong Kong","founded":2014,"stage":"Series B","raised":"$40M","last_round":"$25M Series B","last_date":"Oct 2024","investors":["Chrysalix","Tin Shed Ventures"],"desc":"Zero-emission battery power systems for construction sites. ENERTAINER product.","moat":"Modular BESS for off-grid construction. Asian market focus.","customers":["China construction","Hong Kong infrastructure"],"trl":8,"mp":11,"tm":11,"cr":12,"sr":9,"kf":12,"ep":7,"score":62,"korea":["Samsung C&T","Hyundai Engineering","GS Engineering"],"acquirer":["Atlas Copco","Aggreko"],"thesis":"Construction decarbonization + Asia market = underserved niche.","risk":"Small TAM. Geographic concentration.","url":"https://ampdgroup.com"},

{"id":"leap-energy","sector":"DC Power & BTM","sub":"Demand Response","name":"Leap","country":"USA","founded":2017,"stage":"Series B+","raised":"$59.6M","last_round":"$16M Series B-EXT","last_date":"Nov 2023","investors":["Standard Investments (lead)","Union Square Ventures","Congruent Ventures","National Grid Partners","DNV Ventures"],"desc":"VPP aggregation platform. Connects DER to CAISO, ERCOT, PJM markets.","moat":"ISO market integration across 3 major US grids. API-first developer platform.","customers":["Utilities","Energy retailers","C&I aggregators"],"trl":8,"mp":15,"tm":14,"cr":13,"sr":8,"kf":11,"ep":9,"score":70,"korea":["KEPCO","KT","SK E&S"],"acquirer":["Enel X","Schneider","AutoGrid"],"thesis":"VPP = AI DC demand response aggregator. ISO access moat.","risk":"Competition from Voltus, Enel X. Regulatory complexity.","url":"https://leap.ac"},

{"id":"redwood-materials","sector":"DC Power & BTM","sub":"Battery Recycling","name":"Redwood Materials","country":"USA","founded":2017,"stage":"Series E","raised":"$425M","last_round":"$425M Series E (Eclipse+NVentures led)","last_date":"Jan 2026 (final close)","investors":["Eclipse (lead)","NVentures","Google","Goldman Sachs","Capricorn","T. Rowe Price","Ford","Panasonic"],"desc":"Battery recycling and remanufacturing. Closes US battery supply chain.","moat":"JB Straubel (Tesla CTO). 95%+ material recovery. Cathode+anode active material.","customers":["Panasonic","Ford","Toyota","Volvo"],"trl":9,"mp":16,"tm":17,"cr":15,"sr":8,"kf":15,"ep":9,"score":80,"korea":["Samsung SDI","LG Energy","SK On","POSCO"],"acquirer":["BASF","Umicore","Glencore"],"thesis":"NVIDIA $350M validates. JB Straubel credibility. US battery supply chain = national security.","risk":"EV adoption curve dependency. Commodity price exposure.","url":"https://www.redwoodmaterials.com"},

{"id":"stem-inc","sector":"DC Power & BTM","sub":"AI-BESS Software","name":"Stem Inc","country":"USA","founded":2009,"stage":"Public (NYSE: STEM)","raised":"Public","last_round":"SPAC 2021","last_date":"2021","investors":["Public markets","Activate Capital"],"desc":"Athena AI platform for BESS optimization. 4.5GW+ managed.","moat":"Hardware-agnostic AI dispatch. 4.5GW data moat.","customers":["Hundreds of C&I","Utilities globally"],"trl":9,"mp":14,"tm":14,"cr":16,"sr":7,"kf":12,"ep":8,"score":71,"korea":["Samsung SDI","LG Energy","SK On","KEPCO"],"acquirer":["Fluence","Schneider","ABB"],"thesis":"Hardware-agnostic BESS AI. 4.5GW AUM = data network effect.","risk":"Post-SPAC pressure. Fluence IQ competition.","url":"https://www.stem.com"},

{"id":"natel-energy","sector":"DC Power & BTM","sub":"Hydropower","name":"Natel Energy","country":"USA","founded":2009,"stage":"Series B","raised":"$70M","last_round":"$25M Series B","last_date":"Oct 2024","investors":["Breakthrough Energy","Prelude"],"desc":"Fish-safe restoration hydro turbines for small streams. Distributed clean baseload.","moat":"Fish-safe design. 100kW-5MW range. Minimal civil works.","customers":["Rural utilities","Industrial"],"trl":8,"mp":10,"tm":13,"cr":11,"sr":10,"kf":8,"ep":7,"score":59,"korea":["K-water","KEPCO"],"acquirer":["Andritz","Voith","GE Vernova"],"thesis":"Niche distributed baseload. Small market but defensible.","risk":"Small TAM. Site-specific installs limit scale.","url":"https://natelenergy.com"},

{"id":"swell-energy","sector":"DC Power & BTM","sub":"VPP","name":"Swell Energy","country":"USA","founded":2014,"stage":"Series B","raised":"$120M","last_round":"Opower-Oracle interest","last_date":"2024","investors":["Aligned Climate Capital","Fifth Wall","EIP"],"desc":"Virtual power plant software aggregating distributed BESS for grid services.","moat":"50,000+ VPP enrollments. Hawaiian Electric + SCE utility partnerships.","customers":["Hawaiian Electric","Southern California Edison"],"trl":9,"mp":14,"tm":12,"cr":15,"sr":7,"kf":10,"ep":9,"score":67,"korea":["KEPCO","KT","LG Uplus"],"acquirer":["Oracle","Itron","Landis+Gyr"],"thesis":"Utility VPP = standard. 50K enrolled assets = network moat.","risk":"Oracle acquisition interest. AutoGrid competition.","url":"https://swellenergy.com"},

{"id":"relectrify","sector":"DC Power & BTM","sub":"Battery Reuse","name":"Relectrify","country":"Australia","founded":2016,"stage":"Series A","raised":"$20M","last_round":"$13M Series A","last_date":"Oct 2024","investors":["ARENA","Toyota Ventures","Breakthrough Energy"],"desc":"Second-life EV battery management. Cell-level BMS for heterogeneous packs.","moat":"50% cost reduction vs new BESS. Toyota validation.","customers":["Toyota","Australian utilities"],"trl":7,"mp":12,"tm":14,"cr":10,"sr":11,"kf":14,"ep":9,"score":70,"korea":["Hyundai","Kia","LG Energy","SK On","Samsung SDI"],"acquirer":["Toyota","LG Energy","Umicore"],"thesis":"EV battery wave = 2nd-life opportunity. Korea EV makers = natural partners.","risk":"Cell variability. Regulatory uncertainty for 2nd-life safety.","url":"https://relectrify.com"},

{"id":"xendee","sector":"DC Power & BTM","sub":"Microgrid Design","name":"Xendee","country":"USA","founded":2014,"stage":"Series A","raised":"$15M","last_round":"$10M Series A","last_date":"2022","investors":["Chevron Tech Ventures","DOE"],"desc":"Microgrid design and optimization software. 20,000+ designs completed.","moat":"Techno-economic optimization engine. 20K design library.","customers":["Military","Utilities","C&I"],"trl":8,"mp":11,"tm":12,"cr":11,"sr":7,"kf":9,"ep":7,"score":57,"korea":["KEPCO Engineering","Hyundai Engineering"],"acquirer":["Schneider","Eaton","Black & Veatch"],"thesis":"Design software for exploding microgrid market. Low capex.","risk":"Small team. Niche software market.","url":"https://xendee.com"},

{"id":"ess-inc","sector":"DC Power & BTM","sub":"Iron Flow Battery","name":"ESS Inc","country":"USA","founded":2011,"stage":"Public (NYSE: GWH)","raised":"Public","last_round":"SPAC 2021","last_date":"2021","investors":["SoftBank","Breakthrough Energy","Chevron"],"desc":"Iron flow battery. 4-12 hour duration. All-iron chemistry. No toxic materials.","moat":"All-iron electrolyte. No vanadium. 20-year cycle life.","customers":["Xcel Energy","Portland General Electric"],"trl":8,"mp":13,"tm":14,"cr":10,"sr":11,"kf":9,"ep":7,"score":64,"korea":["LG Energy","Samsung SDI","SK Innovation"],"acquirer":["NextEra","Fluence","Samsung SDI"],"thesis":"Iron flow = no supply chain risk. 20yr life matches utility assets.","risk":"Post-SPAC. Lower density than Li-ion. Commercial scale slow.","url":"https://essinc.com"},

{"id":"gridmatic","sector":"DC Power & BTM","sub":"Energy Trading AI","name":"Gridmatic","country":"USA","founded":2017,"stage":"Series B","raised":"$45M","last_round":"$16M Series B-EXT","last_date":"Nov 2023","investors":["EIP","Congruent Ventures"],"desc":"AI-powered energy trading for renewable assets and BESS. CAISO/ERCOT optimization.","moat":"ML price forecasting. Real-time ISO optimization.","customers":["Renewable IPPs","BESS operators"],"trl":8,"mp":13,"tm":15,"cr":12,"sr":7,"kf":9,"ep":8,"score":64,"korea":["Korea Power Exchange","SK E&S","GS EPS"],"acquirer":["Wood Mackenzie","Aurora Energy","Palantir"],"thesis":"AI trading = BESS optimization critical. As BESS scales, optimization premium grows.","risk":"Niche. Difficult to scale beyond West US.","url":"https://www.gridmatic.com"},

{"id":"ampt","sector":"DC Power & BTM","sub":"Power Electronics","name":"AMPT","country":"USA","founded":2007,"stage":"Series C","raised":"$80M","last_round":"$40M Series C","last_date":"Oct 2024","investors":["Breakthrough Energy","DCVC","Congruent"],"desc":"String optimizer for large-scale solar+storage. 5-10% energy yield improvement.","moat":"Module-level power electronics. Nextracker partnership.","customers":["Nextracker","Array Technologies","Utility solar"],"trl":9,"mp":13,"tm":14,"cr":14,"sr":8,"kf":11,"ep":8,"score":68,"korea":["Hanwha Q Cells","LG Energy","Samsung SDI"],"acquirer":["SolarEdge","Enphase","SMA"],"thesis":"Solar+storage optimization embedded in large projects.","risk":"SolarEdge competition. Module-level electronics commoditizing.","url":"https://ampt.com"},

{"id":"quidnet-energy","sector":"DC Power & BTM","sub":"Geomechanical Storage","name":"Quidnet Energy","country":"USA","founded":2014,"stage":"Series B","raised":"$50M","last_round":"$25M Series B","last_date":"Oct 2024","investors":["Breakthrough Energy","GE Ventures","AP Ventures"],"desc":"Underground water pressure storage. Repurposes oil/gas wells.","moat":"Geomechanical pumped hydro. Existing well = minimal new capex.","customers":["Alberta Innovates","DOE pilot"],"trl":6,"mp":12,"tm":15,"cr":7,"sr":12,"kf":8,"ep":7,"score":61,"korea":["POSCO","SK E&S","Korea Resources"],"acquirer":["Oil & gas majors","Infrastructure funds"],"thesis":"Repurposing wells = low capex long-duration. Geographic flexibility.","risk":"Technology risk. Geology dependency. Very early commercial.","url":"https://quidnetenergy.com"},

# ══════════════════════════════════════════
# SECTOR 2: Grid Software (20개)
# ══════════════════════════════════════════
{"id":"amperon","sector":"Grid Software","sub":"Energy Forecasting","name":"Amperon","country":"USA","founded":2018,"stage":"Series B","raised":"~$29.9M","last_round":"Samsung Ventures","last_date":"Jan 14, 2026","investors":["Samsung Ventures","National Grid Partners","Acario (Tokyo Gas CVC)","EIP"],"desc":"AI energy forecasting for utilities and ISOs. 27 countries. Real-time load forecasting.","moat":"10+ years grid data ML. ISO/RTO integrations. Samsung validates Korea expansion.","customers":["ERCOT","NV Energy","Major utilities 27 countries"],"trl":9,"mp":17,"tm":16,"cr":15,"sr":6,"kf":14,"ep":9,"score":77,"korea":["KEPCO","KPX","Samsung C&T","SK E&S"],"acquirer":["S&P Global","Wood Mackenzie","Oracle","AutoGrid"],"thesis":"AI load forecasting mandatory as AI DC volatility hits grids. Samsung = Korea entry.","risk":"AutoGrid competition. ISO procurement cycles slow.","url":"https://www.amperon.co"},

{"id":"gridbeyond","sector":"Grid Software","sub":"Grid Optimization","name":"GridBeyond","country":"Ireland/USA","founded":2010,"stage":"Series C+","raised":"$89.9M","last_round":"€12M equity round (Samsung Ventures led)","last_date":"Mar 17, 2026","investors":["Samsung Ventures (lead)","ABB","EIP","Constellation Technology Ventures","Alantra","Klima","Mirova","Act Venture Capital","Yokogawa","EDP","Enterprise Ireland"],"desc":"AI grid optimization and DER trading. 2.6GW+ assets managed across 5 markets.","moat":"Multi-market DR: UK/Ireland/US/Japan/Australia. Real-time AI bidding.","customers":["Utilities","Large C&I","Industrial operators"],"trl":9,"mp":16,"tm":15,"cr":15,"sr":7,"kf":13,"ep":9,"score":75,"korea":["KEPCO","KPX","GS EPS","SK E&S"],"acquirer":["ABB","Schneider","Enel X","Oracle"],"thesis":"Multi-market DR = network moat. Samsung+ABB+EIP = credibility.","risk":"Each market has different regulations. Enel X competition.","url":"https://gridbeyond.com"},

{"id":"utilidata","sector":"Grid Software","sub":"Grid Edge Intelligence","name":"Utilidata","country":"USA","founded":2012,"stage":"Series C","raised":"$126.5M","last_round":"$60.3M Series C","last_date":"Apr 2025","investors":["Renown Capital Partners (lead)","NVIDIA","Quanta Services","Keyframe Capital","Microsoft"],"desc":"NVIDIA Jetson-powered smart meters. AI at grid edge for real-time load intelligence.","moat":"NVIDIA partnership. On-device AI inference at meter. 1ms latency.","customers":["National Grid","Green Mountain Power"],"trl":8,"mp":16,"tm":17,"cr":13,"sr":9,"kf":12,"ep":10,"score":77,"korea":["KEPCO","Korea Smart Grid","Samsung Electronics","LG CNS"],"acquirer":["NVIDIA","Itron","Landis+Gyr","Honeywell"],"thesis":"NVIDIA on grid edge = AI DC load management at source.","risk":"AMI replacement cycle 10-15 years. Hardware deployment slow.","url":"https://utilidata.com"},

{"id":"kevala","sector":"Grid Software","sub":"Grid Analytics","name":"Kevala","country":"USA","founded":2014,"stage":"Series A","raised":"$35.8M","last_round":"$21M Series A","last_date":"Aug 2021","investors":["C5 Capital (lead)","Thin Line Capital","Constellation Technology Ventures","Emerson Ventures","Exelon"],"desc":"Grid data analytics. Hosting capacity, EV siting, AI DC interconnection planning.","moat":"Comprehensive grid topology DB. Hosting capacity analysis at scale.","customers":["PG&E","National Grid","Utilities"],"trl":8,"mp":15,"tm":14,"cr":12,"sr":7,"kf":11,"ep":9,"score":68,"korea":["KEPCO","Korea Smart Grid"],"acquirer":["Oracle","Palantir","S&P Global"],"thesis":"AI DC siting = grid data analytics demand. Interconnection maps critical.","risk":"Utility data access challenges. ESRI competition.","url":"https://kevala.com"},

{"id":"voltus","sector":"Grid Software","sub":"Demand Response","name":"Voltus","country":"USA","founded":2016,"stage":"Series C","raised":"$66.2M","last_round":"$31M Series C","last_date":"May 2021","investors":["Activate Capital (lead)","NGP Energy Technology Partners","Prelude Ventures","Ajax Strategies","Union Square Ventures"],"desc":"Virtual power plant for C&I demand response. 2GW+ enrolled capacity.","moat":"Real-time ISO participation: PJM, MISO, CAISO, ERCOT.","customers":["Large industrials","Commercial buildings"],"trl":9,"mp":14,"tm":13,"cr":14,"sr":7,"kf":11,"ep":8,"score":67,"korea":["KEPCO","KPX","SK"],"acquirer":["Enel X","Schneider","AutoGrid"],"thesis":"C&I DR aggregation. AI DC as largest DR resource pool.","risk":"AutoGrid (Enel) competition. Leap.","url":"https://www.voltus.co"},

{"id":"power-factors","sector":"Grid Software","sub":"Asset Management","name":"Power Factors","country":"USA","founded":2015,"stage":"PE-backed","raised":"PE-backed","last_round":"Vista Equity acquisition","last_date":"2021","investors":["Vista Equity Partners"],"desc":"Renewable asset performance management. 100GW+ on platform.","moat":"Single pane of glass. 100GW AUM. BlackRock, Brookfield clients.","customers":["BlackRock","Brookfield","Major IPPs globally"],"trl":9,"mp":14,"tm":13,"cr":17,"sr":6,"kf":12,"ep":9,"score":71,"korea":["Korea Midland Power","SK E&S","Hanwha Q Cells"],"acquirer":["Invenergy","GE Digital","Uplight"],"thesis":"100GW AUM = sticky recurring revenue. PE = near-term exit.","risk":"Vista dynamics. GE Digital competition.","url":"https://www.powerfactors.com"},

{"id":"prescient","sector":"Grid Software","sub":"Grid Planning","name":"Prescient","country":"USA","founded":2019,"stage":"Series A","raised":"$15M","last_round":"$12M Series A","last_date":"Oct 2024","investors":["EIP","Village Capital"],"desc":"AI transmission planning and interconnection study acceleration. 10x faster.","moat":"Reduces 4-year queue study to months. FERC reform tailwind.","customers":["ISOs","Transmission developers"],"trl":7,"mp":16,"tm":15,"cr":11,"sr":8,"kf":10,"ep":9,"score":69,"korea":["KEPCO","Korea Electric Power"],"acquirer":["GE Vernova","S&P Global","ABB"],"thesis":"2,290GW queue = massive demand for faster studies.","risk":"Government/ISO procurement very slow.","url":"https://prescient.ai"},

{"id":"electron","sector":"Grid Software","sub":"Flexibility Market","name":"Electron","country":"UK","founded":2015,"stage":"Series A","raised":"~$9M","last_round":"£4M Series A","last_date":"Sep 2023","investors":["East Innovate (lead)","Riverstone Ventures","Nesta","One Planet Capital"],"desc":"Flexibility marketplace connecting DER to grid markets. UK/EU focus.","moat":"Ofgem-backed platform. Standardized UK flexibility market APIs.","customers":["National Grid ESO","UK DNOs"],"trl":9,"mp":14,"tm":13,"cr":13,"sr":8,"kf":9,"ep":8,"score":65,"korea":["KEPCO","KPX"],"acquirer":["National Grid","Enel X","Elexon"],"thesis":"UK energy reform creates flexibility platform demand. Regulatory tailwind.","risk":"UK-specific. Regulatory change risk.","url":"https://www.electron.org.uk"},

{"id":"innowatts","sector":"Grid Software","sub":"Energy Analytics","name":"Innowatts","country":"USA","founded":2013,"stage":"Acquired (GridX)","raised":"~$30M","last_round":"Acquired by GridX","last_date":"2024","investors":["Energy Impact Partners (lead)","Shell Ventures","Iberdrola Ventures","Evergy Ventures","Energy & Environment Investment"],"desc":"AI energy analytics for retail energy providers. Customer-level load disaggregation.","moat":"10M+ meter data points. Customer-level disaggregation.","customers":["Retail energy providers","Utilities US/EU"],"trl":8,"mp":12,"tm":13,"cr":13,"sr":7,"kf":9,"ep":8,"score":62,"korea":["KEPCO","KPX","GS EPS"],"acquirer":["Oracle","Itron","SAP"],"thesis":"AI DC creates retail energy complexity. Load disaggregation at meter level.","risk":"Oracle Opower competition. Bidgee.","url":"https://innowatts.com"},

{"id":"urbint","sector":"Grid Software","sub":"AI Safety","name":"Urbint","country":"USA","founded":2015,"stage":"Acquired (Itron $325M)","raised":"$144M","last_round":"Acquired by Itron","last_date":"Oct 2025","investors":["Energize Ventures (lead C)","Energy Impact Partners","National Grid Partners","Piva Capital","Salesforce Ventures","Blue Bear Capital","S2G Ventures"],"desc":"AI for utility worker safety and grid infrastructure risk prediction.","moat":"1B+ utility data points. Predictive AI for asset failure, worker safety.","customers":["National Grid","Con Edison","PG&E"],"trl":9,"mp":13,"tm":14,"cr":14,"sr":6,"kf":10,"ep":9,"score":66,"korea":["KEPCO","Korea Gas"],"acquirer":["IBM","Palantir","Oracle"],"thesis":"Utility AI safety = regulatory compliance driver. Sticky once deployed.","risk":"Long utility procurement. Each customer needs data integration.","url":"https://urbint.com"},

{"id":"virtual-peaker","sector":"Grid Software","sub":"VPP Platform","name":"Virtual Peaker","country":"USA","founded":2015,"stage":"Series A","raised":"$31.2M","last_round":"$16.6M Series A","last_date":"2022","investors":["Moore Strategic Ventures (lead)","Emerson Ventures","Veriten","FreshTracks Capital","Chrysalis Ventures"],"desc":"SaaS VPP platform for utilities. Manages thermostats, EVs, BESS for grid services.","moat":"Utility white-label. 50+ utility integrations. API-first.","customers":["Louisville Gas & Electric","Kentucky Utilities","50+ utilities"],"trl":9,"mp":13,"tm":12,"cr":14,"sr":6,"kf":10,"ep":8,"score":63,"korea":["KEPCO","KT","LG Uplus"],"acquirer":["Itron","Oracle Opower","Landis+Gyr"],"thesis":"Utility SaaS VPP. EV/BESS penetration makes VPP mandatory.","risk":"Utility budget constraints. Long sales cycles.","url":"https://virtualpeaker.com"},

{"id":"powerley","sector":"Grid Software","sub":"Home Energy","name":"Powerley","country":"USA","founded":2012,"stage":"Series C","raised":"$40M","last_round":"$15M Series C","last_date":"2022","investors":["EIP","Detroit Edison"],"desc":"Home energy management for utilities. Smart meter data analytics.","moat":"DTE Energy partnership. Utility white-label.","customers":["DTE Energy","Multiple utilities"],"trl":9,"mp":11,"tm":11,"cr":13,"sr":6,"kf":9,"ep":7,"score":57,"korea":["KEPCO","Korea Gas"],"acquirer":["Oracle Opower","Uplight","Itron"],"thesis":"Home energy as demand response aggregation. V2H integration coming.","risk":"Oracle Opower competition. Slow utility adoption.","url":"https://www.powerley.com"},

{"id":"sievert-ai","sector":"Grid Software","sub":"Nuclear AI","name":"Sievert AI","country":"USA","founded":2023,"stage":"Seed","raised":"$5M","last_round":"$5M Seed","last_date":"2024","investors":["Lowercarbon Capital","Homebrew"],"desc":"AI for nuclear plant operations. Predictive maintenance and safety monitoring.","moat":"NRC-grade AI safety framework. Nuclear domain expertise.","customers":["Undisclosed nuclear operators"],"trl":5,"mp":14,"tm":14,"cr":6,"sr":12,"kf":12,"ep":8,"score":64,"korea":["KEPCO","KHNP","Korea Hydro Nuclear"],"acquirer":["GE Vernova Hitachi","Westinghouse","KHNP"],"thesis":"Nuclear renaissance + AI DC offtake = nuclear O&M AI demand spike.","risk":"NRC certification extremely difficult. Very early.","url":"https://sievert.ai"},

{"id":"smart-wires","sector":"Grid Equipment","sub":"Grid Control","name":"Smart Wires","country":"USA/UK","founded":2012,"stage":"PE-backed","raised":"$280M","last_round":"$50M Series D","last_date":"Oct 2024","investors":["National Grid Partners","Prelude","EIP"],"desc":"PowerLine Guardian — modular grid flow control. Reduces transmission congestion.","moat":"2-year install vs 10-year new line. No new permits. Plug-and-play FACTS.","customers":["National Grid","NYPA","Duke Energy"],"trl":9,"mp":15,"tm":15,"cr":13,"sr":8,"kf":11,"ep":9,"score":71,"korea":["KEPCO","LS Electric","HD Hyundai Electric"],"acquirer":["GE Vernova","Siemens Energy","ABB"],"thesis":"Grid congestion = Smart Wires market. 2yr vs 10yr = no-brainer.","risk":"Utility procurement slow. Established FACTS players.","url":"https://smartwires.com"},

{"id":"exodigo","sector":"Grid Software","sub":"Underground Mapping","name":"Exodigo","country":"Israel/USA","founded":2021,"stage":"Series B","raised":"$214M","last_round":"$61M Series B","last_date":"Oct 2024","investors":["Ahren Innovation","Tiger Global","Headline"],"desc":"AI underground infrastructure mapping. Prevents cable/pipe strikes in grid construction.","moat":"Multi-sensor fusion + AI. 10x faster than traditional. Safety regulation driver.","customers":["National Grid","PG&E","UK utilities"],"trl":8,"mp":14,"tm":15,"cr":13,"sr":8,"kf":11,"ep":9,"score":70,"korea":["KEPCO","Korea Gas","Seoul Facilities"],"acquirer":["Trimble","Leica","Hexagon"],"thesis":"Every grid upgrade = Exodigo needed. Dig-safe + AI = safety compliance.","risk":"Hardware + software integration. Weather dependency.","url":"https://exodigo.com"},

{"id":"piclo","sector":"Grid Software","sub":"Flexibility Market","name":"Piclo","country":"UK","founded":2015,"stage":"Series B","raised":"$20M","last_round":"$12M Series B","last_date":"Oct 2024","investors":["Octopus Ventures","Scottish Power Ventures"],"desc":"Flexibility marketplace for UK DNOs. Ofgem-backed standard platform.","moat":"Ofgem backing. Western Power Distribution = National Grid partnership.","customers":["Western Power Distribution","UK DNOs"],"trl":8,"mp":13,"tm":12,"cr":12,"sr":8,"kf":8,"ep":8,"score":61,"korea":["KEPCO"],"acquirer":["National Grid","Centrica","Enel X"],"thesis":"UK DNO flexibility mandated by Ofgem. Regulatory tailwind.","risk":"UK-specific. Regulatory change risk.","url":"https://piclo.energy"},

{"id":"energy-web","sector":"Grid Software","sub":"Blockchain Energy","name":"Energy Web","country":"Switzerland","founded":2017,"stage":"Foundation","raised":"$10M+","last_round":"Foundation model","last_date":"ongoing","investors":["Rocky Mountain Institute","Shell","Siemens"],"desc":"Open-source blockchain for energy. Green certificate tracking, DER registration.","moat":"Energy Web Chain. 100+ energy companies. EW-DOS for DER.","customers":["Shell","Siemens","VW","Utilities globally"],"trl":8,"mp":11,"tm":12,"cr":9,"sr":8,"kf":9,"ep":6,"score":55,"korea":["KEPCO","Korea Certification Board"],"acquirer":["Not M&A — open source"],"thesis":"Green certificate tracking as RE100 reporting grows.","risk":"Blockchain energy niche. Revenue model unclear.","url":"https://www.energyweb.org"},

{"id":"energyos","sector":"Grid Software","sub":"Utility OS","name":"EnergyOS","country":"USA","founded":2024,"stage":"Seed","raised":"$8M","last_round":"$8M Seed","last_date":"2024","investors":["Breakthrough Energy","DCVC"],"desc":"Cloud-native operating system for utility grid operations. Replaces legacy SCADA.","moat":"Microservices vs legacy monolith. Cloud-native = 10x faster updates.","customers":["Pilot utilities"],"trl":5,"mp":14,"tm":15,"cr":5,"sr":12,"kf":10,"ep":8,"score":64,"korea":["KEPCO IT","LG CNS","Samsung SDS"],"acquirer":["Oracle","IBM","GE Vernova"],"thesis":"Legacy SCADA replacement = massive market. Cloud-native wins eventually.","risk":"Very early. Utility IT procurement extremely conservative.","url":"https://energyos.com"},

{"id":"gridware","sector":"Grid Software","sub":"Grid Monitoring","name":"Gridware","country":"USA","founded":2020,"stage":"Series B","raised":"$97.3M","last_round":"$55M Series B","last_date":"Nov 2025","investors":["Tiger Global (lead)","Generation Investment Management","Sequoia Capital","Fifty Years","Lowercarbon Capital","True Ventures","Convective Capital","Y Combinator"],"desc":"IoT sensors for power line monitoring. Wildfire and outage detection.","moat":"Non-contact line sensors. AI fault prediction. <1 second detection.","customers":["PG&E","Arizona Public Service"],"trl":8,"mp":13,"tm":14,"cr":12,"sr":8,"kf":10,"ep":8,"score":65,"korea":["KEPCO","Korea Smart Grid"],"acquirer":["Itron","Landis+Gyr","S&C Electric"],"thesis":"Wildfire liability + AI DC reliability = same grid monitoring need.","risk":"West Coast wildfire-specific initially.","url":"https://gridware.io"},

{"id":"powerbridge","sector":"Grid Software","sub":"Grid Planning","name":"Neara","country":"Australia","founded":2016,"stage":"Series D","raised":"~$130M","last_round":"$90M Series D","last_date":"Feb 2026","investors":["TCV (lead)","EQT","Partners Group","Square Peg Capital","Skip Capital","Prosus Ventures"],"desc":"3D digital twin for power network asset management. AI grid planning.","moat":"3D lidar + AI. Full network digital twin. PG&E partnership.","customers":["PG&E","Western Power","UK utilities"],"trl":8,"mp":14,"tm":15,"cr":13,"sr":8,"kf":10,"ep":9,"score":69,"korea":["KEPCO","Korea Smart Grid"],"acquirer":["Siemens","ABB","GE Vernova"],"thesis":"Grid digital twin = AI DC interconnection planning accelerator.","risk":"Competition from Bentley Systems. Data acquisition cost.","url":"https://www.neara.com"},

# ══════════════════════════════════════════
# SECTOR 3: ESS / LDES (20개)
# ══════════════════════════════════════════
{"id":"noon-energy","sector":"ESS / LDES","sub":"CO2 Battery","name":"Noon Energy","country":"USA","founded":2018,"stage":"Series B","raised":"$63.8M","last_round":"1GW/100GWh supply agreement with Meta","last_date":"Apr 2026","investors":["At One Ventures","Clean Energy Ventures","Aramco Ventures","Emerson Collective","TechEnergy Ventures","Prime Impact Fund","California Energy Commission"],"desc":"100-hour carbon-oxygen battery. Zero degradation. 24/7 CFE for AI DC.","moat":"CO2 electrochemistry. Abundant materials. No lithium/cobalt. 100hr = unique.","customers":["Meta (1GW/100GWh reservation)"],"trl":6,"mp":17,"tm":18,"cr":7,"sr":14,"kf":12,"ep":8,"score":76,"korea":["Samsung SDI","LG Energy","POSCO","SK Innovation"],"acquirer":["Breakthrough Energy portfolio","Strategic utility"],"thesis":"Meta 1GW = most credible LDES commercial contract. CO2 = zero supply chain risk.","risk":"TRL 6. 25MW pilot 2028 before 1GW. Manufacturing unproven.","url":"https://www.noon.energy"},

{"id":"form-energy","sector":"ESS / LDES","sub":"Iron-Air","name":"Form Energy","country":"USA","founded":2017,"stage":"Series F","raised":"$1.43B","last_round":"$405M Series F","last_date":"Oct 2024","investors":["T. Rowe Price (lead)","GE Vernova","TPG Rise Climate","Breakthrough Energy","ArcelorMittal","EIP","Temasek","GIC","Prelude Ventures","Coatue"],"desc":"Iron-air battery. 100-hour duration. $20/kWh target. Michigan factory operational.","moat":"Iron = abundant, cheap. Reversible rusting. Michigan factory live.","customers":["Great River Energy","Georgia Power","PacifiCorp"],"trl":8,"mp":16,"tm":17,"cr":11,"sr":11,"kf":12,"ep":8,"score":75,"korea":["POSCO (steel)","LG Energy","Samsung SDI","Hyundai"],"acquirer":["GE Vernova","ArcelorMittal","Utility strategic"],"thesis":"Best-funded LDES. Factory operational. GE Vernova = grid integration.","risk":"Manufacturing scale. $20/kWh not yet achieved at scale.","url":"https://formenergy.com"},

{"id":"rondo-energy","sector":"ESS / LDES","sub":"Thermal Storage","name":"Rondo Energy","country":"USA","founded":2020,"stage":"Series B","raised":"$107M+","last_round":"$60M Series B (SCG led)","last_date":"Aug 2023","investors":["Breakthrough Energy Ventures","SCG (lead Series B)","Microsoft Climate Innovation Fund","Rio Tinto","Aramco Ventures","SABIC","Energy Impact Partners","H&M Group","John Doerr"],"desc":"Heat battery stores renewable as 1500°C heat. Industrial decarbonization.","moat":"1500°C = only solution for industrial heat. 90% of industrial energy is heat.","customers":["Calgren Renewable Fuels","Industrial manufacturers"],"trl":8,"mp":14,"tm":16,"cr":11,"sr":9,"kf":13,"ep":8,"score":71,"korea":["POSCO","Hyundai Steel","Samsung SDI","LG Chem"],"acquirer":["BASF","Siemens Energy","GE Vernova"],"thesis":"Industrial heat = 90% of energy use. No other 1500°C solution.","risk":"Industrial sales cycles very long. Electrolyzer competition.","url":"https://rondoenergy.com"},

{"id":"highview-power","sector":"ESS / LDES","sub":"Liquid Air","name":"Highview Power","country":"UK","founded":2005,"stage":"Late Stage","raised":"£500M+","last_round":"£130M (Hunterston)","last_date":"Nov 2025","investors":["UK Infrastructure Bank (lead)","Centrica","Goldman Sachs","Rio Tinto","KIRKBI","Scottish National Investment Bank","Mosaic Capital","Sumitomo Heavy Industries"],"desc":"CRYOBattery — liquid air energy storage. 2-200hr. GW-scale potential.","moat":"Cryogenic air = abundant. No geography constraints. 30yr life.","customers":["Pilot UK/US/EU"],"trl":7,"mp":13,"tm":14,"cr":8,"sr":13,"kf":10,"ep":7,"score":65,"korea":["POSCO","Hanwha","Samsung C&T"],"acquirer":["Sumitomo (existing)","Infrastructure funds"],"thesis":"GW-scale LDES abundant materials. UK government backing.","risk":"~50% round-trip efficiency. High capex vs Li-ion short duration.","url":"https://www.highviewpower.com"},

{"id":"ambri","sector":"ESS / LDES","sub":"Liquid Metal","name":"Ambri","country":"USA","founded":2010,"stage":"Restructured (post-Ch11)","raised":"$222M","last_round":"Ch11 bankruptcy + asset sale","last_date":"Aug 2024","investors":["Bill Gates (Gates Frontier)","Reliance Industries","Paulson & Co","Fortistar","KLP","Microsoft (customer/pilot)"],"desc":"Liquid metal battery. Antimony-bismuth. 20+ year no capacity fade.","moat":"Self-sealing liquid metal. 20yr zero fade = unprecedented. Microsoft pilot.","customers":["Microsoft (pilot)"],"trl":7,"mp":13,"tm":15,"cr":7,"sr":14,"kf":9,"ep":7,"score":65,"korea":["Samsung SDI","LG Energy","POSCO"],"acquirer":["Microsoft","Strategic metals"],"thesis":"20yr no-fade = utility-grade asset. Gates + Khosla credibility.","risk":"500°C operating temp. Thermal management challenge. Commercial unproven.","url":"https://ambri.com"},

{"id":"hydrostor","sector":"ESS / LDES","sub":"Compressed Air","name":"Hydrostor","country":"Canada","founded":2010,"stage":"Series D+","raised":"$495M+","last_round":"$200M convertible note","last_date":"Feb 2025","investors":["Goldman Sachs Asset Management","CPP Investments","Canada Growth Fund","ArcTern Ventures","BDC"],"desc":"Advanced compressed air energy storage. Underground caverns. 8-24 hour.","moat":"Water pressure compensation. Constant pressure = high efficiency.","customers":["AGL Energy Australia","Rosamond CA"],"trl":7,"mp":13,"tm":14,"cr":9,"sr":12,"kf":9,"ep":7,"score":64,"korea":["KEPCO","Korea Water Resources"],"acquirer":["Infrastructure funds","Utilities"],"thesis":"Goldman backing. Underground = 30yr asset life.","risk":"Site geology dependency. Long development.","url":"https://www.hydrostor.ca"},

{"id":"eos-energy","sector":"ESS / LDES","sub":"Zinc Battery","name":"Eos Energy","country":"USA","founded":2008,"stage":"Public (NASDAQ: EOSE)","raised":"Public","last_round":"SPAC 2020","last_date":"2020","investors":["Cerberus Capital","Public markets"],"desc":"Zinc hybrid cathode battery. 3-12hr. Non-flammable aqueous.","moat":"Aqueous zinc = non-flammable. 5,000+ cycles. No lithium/cobalt.","customers":["US utilities","Commercial operators"],"trl":8,"mp":12,"tm":12,"cr":9,"sr":11,"kf":8,"ep":6,"score":58,"korea":["Samsung SDI","LG Energy"],"acquirer":["NextEra","Fluence"],"thesis":"Non-flammable = AI DC safe. No supply chain risk.","risk":"Post-SPAC cash burn. Lower density than Li-ion.","url":"https://www.eosenergystorage.com"},

{"id":"energy-vault","sector":"ESS / LDES","sub":"Gravity Storage","name":"Energy Vault","country":"USA/Switzerland","founded":2017,"stage":"Public (NYSE: NRGV)","raised":"Public","last_round":"SPAC 2022","last_date":"2022","investors":["SoftBank","Saudi Aramco"],"desc":"Gravity-based storage using composite bricks. 4-12hr duration.","moat":"EVx gravity tower. Composite brick recycling. Long asset life.","customers":["Atlas Renewable","Enel Green Power"],"trl":8,"mp":11,"tm":11,"cr":9,"sr":12,"kf":7,"ep":6,"score":56,"korea":["POSCO","Korea Electric Power"],"acquirer":["Infrastructure funds"],"thesis":"Gravity = no electrochemistry, no degradation. Low OpEx.","risk":"Post-SPAC. Marginal vs Li-ion economics.","url":"https://energyvault.com"},

{"id":"quidnet-ldes","sector":"ESS / LDES","sub":"Geomechanical","name":"Gravitricity","country":"UK","founded":2018,"stage":"Series A","raised":"$12M","last_round":"£9M Series A","last_date":"2022","investors":["Innovate UK","Scottish Enterprise"],"desc":"Gravity storage in mine shafts. Fast response (<1 second).","moat":"Repurposes mine shafts. <1 second response. Long cycle life.","customers":["UK pilot","South Africa mine"],"trl":6,"mp":11,"tm":12,"cr":6,"sr":12,"kf":7,"ep":6,"score":54,"korea":["Korea Resources Corp"],"acquirer":["Mining companies","Infrastructure"],"thesis":"Repurposes existing mine infrastructure. No new excavation.","risk":"Limited to mine shaft locations. Small scale.","url":"https://gravitricity.com"},

{"id":"peak-power","sector":"ESS / LDES","sub":"AI BESS Optimization","name":"Peak Power","country":"Canada","founded":2017,"stage":"Series B","raised":"$30M","last_round":"$16M Series B-EXT","last_date":"Nov 2023","investors":["Investissement Québec","BDC Capital"],"desc":"AI-powered BESS optimization for C&I. Demand charge reduction.","moat":"Predictive ML for demand peaks. Automated BESS dispatch.","customers":["Canadian C&I operators"],"trl":8,"mp":11,"tm":12,"cr":12,"sr":7,"kf":8,"ep":7,"score":57,"korea":["SK","LG","Samsung"],"acquirer":["Stem Inc","AutoGrid"],"thesis":"C&I demand charge reduction = fast ROI. Canada validation.","risk":"Small market. US expansion needed.","url":"https://www.peakpowerenergy.com"},

{"id":"salient-energy","sector":"ESS / LDES","sub":"Zinc Ion","name":"Salient Energy","country":"Canada","founded":2018,"stage":"Series A","raised":"$20M","last_round":"$15M Series A","last_date":"2024","investors":["Equinor Ventures","Evok Innovations"],"desc":"Zinc-ion batteries. Drop-in Li-ion replacement. Non-flammable aqueous.","moat":"Drop-in form factor. Non-flammable = AI DC safe. Low integration cost.","customers":["Canadian C&I"],"trl":7,"mp":12,"tm":13,"cr":9,"sr":10,"kf":9,"ep":7,"score":60,"korea":["Samsung SDI","LG Energy"],"acquirer":["Samsung SDI","LG Energy"],"thesis":"Drop-in = low integration. Non-flammable = AI DC safety compliance.","risk":"Lower energy density. Manufacturing scale.","url":"https://salientenergy.ca"},

{"id":"invinity","sector":"ESS / LDES","sub":"Vanadium Flow","name":"Invinity Energy Systems","country":"UK","founded":2020,"stage":"Public (AIM: IES)","raised":"Public","last_round":"AIM listing","last_date":"2020","investors":["Public markets"],"desc":"Vanadium flow batteries. 4-10hr. No degradation. 25yr life.","moat":"Vanadium = no degradation. Electrolyte recyclable. 25yr = utility asset life.","customers":["Commercial buildings","Utilities US/UK/Asia"],"trl":9,"mp":12,"tm":12,"cr":11,"sr":10,"kf":10,"ep":7,"score":62,"korea":["Samsung SDI","LS Electric","KEPCO"],"acquirer":["Sumitomo Electric","LS Electric"],"thesis":"25yr life matches utility infrastructure. Vanadium mature tech.","risk":"Vanadium supply chain. Higher cost vs Li-ion short duration.","url":"https://invinity.com"},

{"id":"swell-ldes","sector":"ESS / LDES","sub":"Thermal LDES","name":"Malta Inc (Peak Storage)","country":"USA","founded":2018,"stage":"Series B","raised":"$50M","last_round":"Breakthrough-backed","last_date":"Oct 2024","investors":["Breakthrough Energy","Concord New Energy"],"desc":"Pumped heat electricity storage. Molten salt hot + cold sides.","moat":"Scalable 10MW to GW. No geography constraint. Grid-scale.","customers":["Pilot projects"],"trl":6,"mp":12,"tm":14,"cr":6,"sr":13,"kf":9,"ep":7,"score":62,"korea":["POSCO","Doosan Heavy"],"acquirer":["Infrastructure developer","Utility"],"thesis":"Pumped heat = no geography. Molten salt proven in CSP.","risk":"Efficiency penalty. Early commercial.","url":"https://maltainc.com"},

{"id":"electriq","sector":"ESS / LDES","sub":"Residential BESS","name":"Electriq Power","country":"USA","founded":2014,"stage":"Public (NYSE: ELIQ)","raised":"Public","last_round":"SPAC 2022","last_date":"2022","investors":["Public markets"],"desc":"Residential battery storage. PowerPod. AI-powered home energy.","moat":"Bundled HW+SW+service. AI energy management.","customers":["US homeowners"],"trl":9,"mp":10,"tm":9,"cr":10,"sr":9,"kf":7,"ep":6,"score":51,"korea":["LG Energy","Samsung SDI"],"acquirer":["Sunrun","SunPower"],"thesis":"Residential BESS market growing. VPP enrollment potential.","risk":"Tesla Powerwall competition. Post-SPAC.","url":"https://electriqpower.com"},

{"id":"c2-global","sector":"ESS / LDES","sub":"CO2 Storage","name":"C2 Global Technologies","country":"USA","founded":2019,"stage":"Seed","raised":"$3M","last_round":"$3M Seed","last_date":"Oct 2024","investors":["Climate tech angels"],"desc":"CO2-based energy storage with carbon capture integration.","moat":"Negative carbon storage. CO2 capture during discharge.","customers":["Pilot stage"],"trl":3,"mp":9,"tm":13,"cr":2,"sr":18,"kf":6,"ep":5,"score":53,"korea":["KEPCO","SK Innovation"],"acquirer":["Carbon capture companies"],"thesis":"Negative carbon storage = ultimate dream. Very early.","risk":"TRL 3. Pre-commercial. Carbon pricing required.","url":"https://c2global.com"},

{"id":"gravity-power","sector":"ESS / LDES","sub":"Underground Pumped Hydro","name":"Gravity Power","country":"USA","founded":2011,"stage":"Series A","raised":"$15M","last_round":"$15M Series A","last_date":"2022","investors":["Siemens (strategic)","DOE"],"desc":"Underground pumped hydro using large pistons. No mountain required.","moat":"No geography restriction. Underground shaft. Modular.","customers":["Pilot projects"],"trl":5,"mp":11,"tm":13,"cr":4,"sr":15,"kf":8,"ep":6,"score":57,"korea":["K-water","KEPCO"],"acquirer":["Siemens Energy","Infrastructure developer"],"thesis":"Pumped hydro without geography. Massive potential.","risk":"Very early. Underground shaft engineering.","url":"https://gravitypower.net"},

{"id":"storelectric","sector":"ESS / LDES","sub":"CAES","name":"Storelectric","country":"UK","founded":2013,"stage":"Seed","raised":"$5M","last_round":"$5M Seed","last_date":"Oct 2024","investors":["Innovate UK"],"desc":"Compressed air energy storage in salt caverns. 70%+ round-trip efficiency.","moat":"Thermal store integration. High efficiency. Large scale potential.","customers":["Conceptual projects"],"trl":4,"mp":10,"tm":12,"cr":3,"sr":16,"kf":6,"ep":5,"score":52,"korea":["Korea Resources Corp"],"acquirer":["Infrastructure developer"],"thesis":"Cavern storage = lowest cost LDES if geology available.","risk":"Very early. Salt cavern dependent.","url":"https://storelectric.com"},

{"id":"quidnet-2","sector":"ESS / LDES","sub":"Iron Flow","name":"Avalon Battery","country":"USA","founded":2014,"stage":"Series B","raised":"$50M","last_round":"$30M Series B","last_date":"Oct 2024","investors":["Export Development Canada","BDC"],"desc":"All-vanadium flow battery. Containerized systems for utility scale.","moat":"Containerized = rapid deployment. 20yr electrolyte life.","customers":["Canadian utilities","C&I"],"trl":8,"mp":12,"tm":12,"cr":11,"sr":10,"kf":9,"ep":7,"score":61,"korea":["Samsung SDI","LS Electric"],"acquirer":["Sumitomo","LS Electric"],"thesis":"Containerized deployment = faster go-to-market. Canada utility relationships.","risk":"Vanadium cost. Li-ion competition.","url":"https://avalonbattery.com"},

{"id":"electrowatt","sector":"ESS / LDES","sub":"Zinc Bromine","name":"Gelion","country":"Australia","founded":2015,"stage":"Public (ASX: GEL)","raised":"Public","last_round":"ASX listing","last_date":"2022","investors":["Public markets","Sydney University spinout"],"desc":"Zinc-bromide gel battery. Non-flammable. Cheap materials.","moat":"Gel electrolyte = no liquid spill. Sydney Uni spinout. Non-flammable.","customers":["Australian C&I pilots"],"trl":7,"mp":11,"tm":13,"cr":9,"sr":10,"kf":8,"ep":6,"score":57,"korea":["Samsung SDI","LG Energy"],"acquirer":["Samsung SDI","LG Energy"],"thesis":"Gel = non-flammable + no spill. AI DC fire safety compliance.","risk":"Commercial scale unproven. Li-ion competition.","url":"https://gelion.com"},

# ══════════════════════════════════════════
# SECTOR 4: Grid Equipment (20개)
# ══════════════════════════════════════════
{"id":"hitachi-energy","sector":"Grid Equipment","sub":"HVDC/Transformer","name":"Hitachi Energy","country":"Japan/Switzerland","founded":2020,"stage":"Public (Hitachi sub)","raised":"Hitachi subsidiary","last_round":"ABB Power Grids $11B","last_date":"2020","investors":["Hitachi (80.1%)"],"desc":"HVDC, EHV transformers, grid automation. AI DC interconnection critical supplier.","moat":"EHV transformer backlog 36 months. HVDC Light leader. 3-company global oligopoly.","customers":["Global utilities","Hyperscalers via grid operators"],"trl":10,"mp":18,"tm":17,"cr":18,"sr":8,"kf":14,"ep":5,"score":80,"korea":["KEPCO","HD Hyundai Electric","LS Electric","Hyosung"],"acquirer":["Not acquirable"],"thesis":"Transformer bottleneck = pricing power 2025-2028. AI DC interconnection critical path.","risk":"Hitachi parent strategy. ABB, Siemens competition.","url":"https://www.hitachienergy.com"},

{"id":"ls-electric","sector":"Grid Equipment","sub":"Korean Grid OEM","name":"LS Electric","country":"South Korea","founded":1974,"stage":"Public (KRX: 010120)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["LS Group","Public markets"],"desc":"Korean power equipment leader. Switchgear, transformers, inverters, EV charging.","moat":"KEPCO supplier. US transformer exports growing. GridBeyond co-investor.","customers":["KEPCO","Korean industrials","US utilities"],"trl":9,"mp":15,"tm":14,"cr":16,"sr":7,"kf":20,"ep":6,"score":78,"korea":["KEPCO","Samsung C&T","Hyundai Engineering","SK EPC"],"acquirer":["ABB","Siemens","Eaton"],"thesis":"Korean OEM + US transformer exports + AI DC grid = structural winner.","risk":"Korea concentrated. ABB/Hitachi competition.","url":"https://www.lselectric.co.kr"},

{"id":"hd-hyundai-electric","sector":"Grid Equipment","sub":"Korean Grid OEM","name":"HD Hyundai Electric","country":"South Korea","founded":1977,"stage":"Public (KRX: 267260)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["HD Hyundai Group","Public markets"],"desc":"Transformers, GIS, power cables. Alabama factory serving US AI DC market.","moat":"345kV UHV transformer. Alabama plant proximity to NoVA AI DC cluster.","customers":["US utilities","KEPCO","Global utilities"],"trl":9,"mp":16,"tm":14,"cr":16,"sr":7,"kf":20,"ep":6,"score":79,"korea":["KEPCO","Samsung C&T","SK EPC","GS Engineering"],"acquirer":["ABB","Siemens Energy"],"thesis":"Alabama factory = proximity to Northern Virginia AI DC cluster. UHV capability rare.","risk":"Hitachi/ABB competition. Currency exposure.","url":"https://hdhy-electric.com"},

{"id":"hyosung-heavy","sector":"Grid Equipment","sub":"Korean Transformer","name":"Hyosung Heavy Industries","country":"South Korea","founded":1966,"stage":"Public (KRX: 298040)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["Hyosung Group","Public markets"],"desc":"765kV UHV transformers. Virginia factory serving US East Coast AI DC.","moat":"Virginia factory = Northern Virginia cluster proximity. 765kV = highest voltage tier.","customers":["US utilities East Coast","KEPCO","Global"],"trl":9,"mp":16,"tm":14,"cr":15,"sr":7,"kf":20,"ep":6,"score":78,"korea":["KEPCO","Samsung C&T","Hyundai Engineering"],"acquirer":["ABB","Siemens","GE Vernova"],"thesis":"Virginia plant + UHV capability = Northern Virginia AI DC natural supplier.","risk":"Quality consistency. Hitachi/ABB competition.","url":"https://www.hyosungheavy.com"},

{"id":"vertiv","sector":"Grid Equipment","sub":"DC Power Infrastructure","name":"Vertiv Holdings","country":"USA","founded":2016,"stage":"Public (NYSE: VRT)","raised":"Public","last_round":"KKR Emerson spinoff","last_date":"2020","investors":["KKR","Public markets"],"desc":"Critical digital infrastructure: UPS, thermal management, power distribution for AI DC.","moat":"Full AI DC power stack. 40%+ revenue from AI DC customers. ALL hyperscalers.","customers":["NVIDIA","Microsoft","Google","Amazon","Meta"],"trl":10,"mp":19,"tm":15,"cr":19,"sr":6,"kf":13,"ep":7,"score":79,"korea":["Samsung Electronics","SK Hynix","Naver","KT"],"acquirer":["Eaton","Schneider","ABB"],"thesis":"Every AI DC = Vertiv. 40%+ AI DC revenue = structural winner.","risk":"Premium valuation. Eaton/Schneider competition.","url":"https://www.vertiv.com"},

{"id":"quanta-services","sector":"Grid Equipment","sub":"Grid Construction","name":"Quanta Services","country":"USA","founded":1997,"stage":"Public (NYSE: PWR)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["Public markets"],"desc":"Largest US T&D contractor. 25,000+ lineworkers. AI DC interconnection EPC.","moat":"Labor scale moat. Every transmission project = Quanta contract.","customers":["US utilities","Hyperscalers indirect","Pipelines"],"trl":10,"mp":17,"tm":13,"cr":18,"sr":6,"kf":8,"ep":4,"score":66,"korea":["Samsung C&T","Hyundai Engineering","GS Engineering"],"acquirer":["Not acquirable at scale"],"thesis":"Every grid upgrade = Quanta. AI DC buildout = years of backlog.","risk":"Labor constraint. MYR Group, MasTec competition.","url":"https://quantaservices.com"},

{"id":"prysmian","sector":"Grid Equipment","sub":"Power Cable","name":"Prysmian Group","country":"Italy","founded":1879,"stage":"Public (MIL: PRY)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["Public markets"],"desc":"World's largest cable manufacturer. HV/EHV, subsea, optical fiber.","moat":"Global manufacturing 50+ countries. Subsea cable engineering leadership.","customers":["Global utilities","Hyperscalers","Offshore wind"],"trl":10,"mp":16,"tm":14,"cr":17,"sr":7,"kf":11,"ep":5,"score":65,"korea":["KEPCO","LS Cable","Taihan Electric"],"acquirer":["Not acquirable at scale"],"thesis":"HV cable bottleneck = pricing power. Offshore wind + AI DC structural demand.","risk":"Copper exposure. Nexans competition.","url":"https://www.prysmiangroup.com"},

{"id":"ls-cable","sector":"Grid Equipment","sub":"Korean Cable","name":"LS Cable & System","country":"South Korea","founded":1962,"stage":"Public (KRX: 229640)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["LS Group","Public markets"],"desc":"Korean cable OEM. HV power, submarine, EV charging cables. US/EU expansion.","moat":"Korean dominance. Growing US/EU submarine capacity.","customers":["KEPCO","US utilities","Global offshore"],"trl":9,"mp":14,"tm":13,"cr":15,"sr":7,"kf":20,"ep":6,"score":75,"korea":["KEPCO","Samsung C&T","Hyundai Engineering"],"acquirer":["Prysmian","Nexans"],"thesis":"Korean cable OEM + global footprint growing. AI DC + offshore wind tailwind.","risk":"Global giant competition. Currency.","url":"https://www.lscns.co.kr"},

{"id":"navitas-semi","sector":"Grid Equipment","sub":"GaN Power Semi","name":"Navitas Semiconductor","country":"USA","founded":2014,"stage":"Public (NASDAQ: NVTS)","raised":"Public","last_round":"SPAC 2021","last_date":"2021","investors":["Public markets","TSMC"],"desc":"GaN power ICs. 100x faster, 3x more efficient than silicon. AI DC PDU efficiency.","moat":"GaNFast technology. First GaN IC integrating driver + FET. AI DC PSU leader.","customers":["Dell","Lenovo","AI DC ODMs"],"trl":9,"mp":15,"tm":16,"cr":13,"sr":9,"kf":14,"ep":9,"score":76,"korea":["Samsung Electronics","SK Hynix","LG Electronics","Hyundai Motor"],"acquirer":["Texas Instruments","Infineon","STMicro"],"thesis":"GaN = AI DC power efficiency. Every W saved = less cooling. Power semi supercycle.","risk":"Wolfspeed SiC competition. TSMC dependency.","url":"https://navitassemi.com"},

{"id":"wolfspeed","sector":"Grid Equipment","sub":"SiC Power Semi","name":"Wolfspeed","country":"USA","founded":1987,"stage":"Public (NYSE: WOLF)","raised":"Public","last_round":"DOE $2.5B loan","last_date":"2024","investors":["DOE","Public markets","Infineon (customer)"],"desc":"Silicon Carbide power semiconductors. Largest SiC wafer manufacturer. 200mm capability.","moat":"Only large-scale US SiC maker. Vertical integration. DOE loan = national security asset.","customers":["GM","Renault","BorgWarner"],"trl":9,"mp":14,"tm":16,"cr":13,"sr":11,"kf":12,"ep":8,"score":74,"korea":["Samsung Electronics","Hyundai Motor","LG Electronics","SK On"],"acquirer":["Infineon","STMicro","Renesas"],"thesis":"SiC = grid inverter + EV power. Grid-forming inverter = growing SiC market.","risk":"Cash burn. STMicro, Onsemi competition.","url":"https://www.wolfspeed.com"},

{"id":"nexans","sector":"Grid Equipment","sub":"Power Cable","name":"Nexans","country":"France","founded":2000,"stage":"Public (EPA: NEX)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["Public markets"],"desc":"HV submarine cables, land cables. Pure-play electrification since 2021.","moat":"Aurora submarine cable ship. HVDC expertise. Long-term offshore wind contracts.","customers":["Ørsted","Equinor","National Grid"],"trl":10,"mp":15,"tm":14,"cr":15,"sr":8,"kf":10,"ep":5,"score":62,"korea":["LS Cable","KEPCO","Samsung C&T"],"acquirer":["Not acquirable"],"thesis":"Offshore wind + subsea interconnection = structural cable demand.","risk":"French political risk. Prysmian competition.","url":"https://www.nexans.com"},

{"id":"grid-solutions-ge","sector":"Grid Equipment","sub":"Grid Automation","name":"GE Vernova Grid Solutions","country":"USA","founded":2024,"stage":"Public (GEV sub)","raised":"GEV subsidiary","last_round":"GEV IPO $35B mktcap","last_date":"Apr 2024","investors":["Public markets (GEV parent)"],"desc":"HVDC, grid automation, protection, substations. Emerald AI investor.","moat":"EHV transformer backlog 36mo. Grid-forming inverter leadership. FACTS tech.","customers":["Global utilities","ISO/RTO operators"],"trl":10,"mp":18,"tm":17,"cr":18,"sr":7,"kf":14,"ep":5,"score":79,"korea":["KEPCO","HD Hyundai Electric","LS Electric","Hyosung"],"acquirer":["Not acquirable"],"thesis":"Grid bottleneck = pricing power. Transformer backlog 2025-2028. Emerald AI investor.","risk":"Offshore wind losses. Own capacity limits growth.","url":"https://www.gevernova.com"},

{"id":"itron","sector":"Grid Equipment","sub":"Smart Meter","name":"Itron","country":"USA","founded":1977,"stage":"Public (NASDAQ: ITRI)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["Public markets"],"desc":"Smart meters, grid IoT. 200M+ deployed. AI DC load measurement.","moat":"200M meter base. RIVA mesh network. Utility relationship stickiness.","customers":["200+ utilities globally"],"trl":10,"mp":13,"tm":13,"cr":17,"sr":6,"kf":11,"ep":7,"score":60,"korea":["KEPCO","Korea Gas","Korea Smart Grid"],"acquirer":["Honeywell","Oracle","Siemens"],"thesis":"Meter data = AI DC load analytics. 200M base = sticky.","risk":"Hardware commoditization. Landis+Gyr competition.","url":"https://www.itron.com"},

{"id":"varentec","sector":"Grid Equipment","sub":"Grid Stability","name":"Varentec","country":"USA","founded":2010,"stage":"Series C","raised":"$40M","last_round":"$20M Series C","last_date":"2022","investors":["GE Ventures","Duke Energy","EIP"],"desc":"Advanced volt-VAr optimization for distribution grids. AI DC voltage stability.","moat":"ENGO platform. Real-time distributed voltage control. 15%+ efficiency.","customers":["Duke Energy","PG&E"],"trl":9,"mp":13,"tm":13,"cr":12,"sr":7,"kf":10,"ep":8,"score":63,"korea":["KEPCO","Korea Smart Grid"],"acquirer":["GE Vernova","Siemens","Itron"],"thesis":"AI DC demand = local voltage instability. Voltage management critical.","risk":"Niche product. Very slow utility procurement.","url":"https://varentec.com"},

{"id":"acuity","sector":"Grid Equipment","sub":"Building Energy","name":"Acuity Brands","country":"USA","founded":1907,"stage":"Public (NYSE: AYI)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["Public markets"],"desc":"Intelligent lighting and building management. AI DC facility energy efficiency.","moat":"Atrius IoT platform. 90+ years relationships. AI DC cooling integration.","customers":["Commercial real estate","Hospitals","Universities"],"trl":10,"mp":11,"tm":11,"cr":17,"sr":5,"kf":9,"ep":5,"score":58,"korea":["Samsung SDS","LG CNS"],"acquirer":["Johnson Controls","Honeywell"],"thesis":"Lighting = 20-40% facility energy. AI DC efficiency driver.","risk":"LED commoditization. Limited AI DC direct exposure.","url":"https://www.acuitybrands.com"},

{"id":"s-c-electric","sector":"Grid Equipment","sub":"Grid Protection","name":"S&C Electric","country":"USA","founded":1911,"stage":"Private (employee-owned)","raised":"Private","last_round":"Employee-owned","last_date":"N/A","investors":["Employee-owned"],"desc":"Power switching, protection, smart grid solutions. Automated grid reconfiguration.","moat":"110 years utility relationships. IntelliRupter self-healing grid. Employee-owned = no exit pressure.","customers":["US utilities","International utilities"],"trl":10,"mp":13,"tm":13,"cr":15,"sr":6,"kf":10,"ep":6,"score":63,"korea":["KEPCO","LS Electric","HD Hyundai"],"acquirer":["ABB","Eaton","Siemens"],"thesis":"Self-healing grid = AI DC reliability. 110yr moat difficult to replicate.","risk":"Private/employee-owned limits exit. Conservative management.","url":"https://www.sandc.com"},

{"id":"landis-gyr","sector":"Grid Equipment","sub":"Smart Metering","name":"Landis+Gyr","country":"Switzerland","founded":1896,"stage":"Public (SWX: LAND)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["Public markets"],"desc":"Smart metering and grid edge. 600M+ endpoints. Advanced AMI for utilities.","moat":"600M endpoint ecosystem. Gridstream platform. Long utility contracts.","customers":["200+ utilities globally"],"trl":10,"mp":12,"tm":13,"cr":16,"sr":6,"kf":10,"ep":6,"score":63,"korea":["KEPCO","Korea Gas"],"acquirer":["Honeywell","Siemens","Oracle"],"thesis":"AMI data = AI DC grid intelligence. 600M endpoint = data network effect.","risk":"Itron competition. AMI replacement cycles slow.","url":"https://www.landisgyr.com"},

{"id":"gridbridge","sector":"Grid Equipment","sub":"Power Electronics","name":"GridBridge","country":"USA","founded":2012,"stage":"Acquired (ERMCO-ECI)","raised":"$500K","last_round":"Acquired by ERMCO-ECI","last_date":"Jun 2017","investors":["NSF","DOE grant"],"desc":"Modular power electronics for grid modernization. Solid-state transformer.","moat":"Solid-state transformer = 100x smaller than conventional. ABB backing.","customers":["Duke Energy","National Grid"],"trl":7,"mp":13,"tm":15,"cr":9,"sr":11,"kf":10,"ep":8,"score":66,"korea":["KEPCO","LS Electric"],"acquirer":["ABB (existing investor)","Siemens","GE Vernova"],"thesis":"Solid-state transformer = grid modernization enabler. ABB validation.","risk":"Technology maturity. Cost vs conventional transformer.","url":"https://gridbridge.com"},

# ══════════════════════════════════════════
# SECTOR 5: Cooling & Power Semi (20개)
# ══════════════════════════════════════════
{"id":"asetek","sector":"Cooling & Power Semi","sub":"Liquid Cooling","name":"Asetek","country":"Denmark","founded":2000,"stage":"Public (OSE: ASETEK)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["Public markets"],"desc":"Liquid cooling for HPC and AI GPU clusters. 28M+ units shipped.","moat":"28M units = largest deployed base. Server-direct liquid. GPU thermal expertise.","customers":["Dell","Lenovo","HPE","AI DC operators"],"trl":10,"mp":16,"tm":14,"cr":15,"sr":7,"kf":12,"ep":8,"score":72,"korea":["Samsung Electronics","SK Hynix","Naver","KT"],"acquirer":["Vertiv","Eaton","ABB"],"thesis":"NVIDIA B200 700W = liquid cooling mandatory. Asetek = incumbent.","risk":"Vertiv, nVent competition. Dell/HP internal.","url":"https://www.asetek.com"},

{"id":"iceotope","sector":"Cooling & Power Semi","sub":"Immersion Cooling","name":"Iceotope Technologies","country":"UK","founded":2005,"stage":"Series B","raised":"$81.4M","last_round":"£30M Series B","last_date":"Jul 2022","investors":["ABC Impact (lead)","nVent Electric","Northern Gritstone","British Patient Capital","SDCL","Pavilion Capital"],"desc":"Precision immersion cooling for high-density AI servers.","moat":"Chassis-level immersion. Standard rack hardware compatible. Schneider partnership.","customers":["Schneider Electric","Lenovo","HPC operators"],"trl":8,"mp":15,"tm":14,"cr":12,"sr":9,"kf":13,"ep":9,"score":72,"korea":["Samsung Electronics","SK Hynix","LG","Doosan"],"acquirer":["Schneider (existing)","Vertiv","ABB"],"thesis":"Immersion mandatory for 1000W+ GPU. Schneider = distribution channel.","risk":"Coolant compatibility. Data center retrofit complexity.","url":"https://iceotope.com"},

{"id":"submer","sector":"Cooling & Power Semi","sub":"Immersion Cooling","name":"Submer Technologies","country":"Spain","founded":2015,"stage":"Series C","raised":"$89.5M","last_round":"$55.5M Series C","last_date":"Oct 2024","investors":["M&G (lead)","Planet First Partners","Norrsken VC","Mundi Ventures","Santander"],"desc":"Immersion cooling systems. SmartPodX product. 30% TCO reduction.","moat":"Proprietary dielectric fluid. Full-immersion rack. EU regulatory tailwind.","customers":["Supermicro","European HPC","Crypto miners"],"trl":8,"mp":14,"tm":13,"cr":12,"sr":9,"kf":11,"ep":8,"score":67,"korea":["Samsung Electronics","SK Hynix","LG CNS"],"acquirer":["Vertiv","Schneider","Eaton"],"thesis":"EU PUE regulations + AI density = immersion demand. First-mover Europe.","risk":"Iceotope, Asperitas competition. Fluid dependency.","url":"https://submer.com"},

{"id":"vapor-io","sector":"Cooling & Power Semi","sub":"Edge DC","name":"Vapor IO","country":"USA","founded":2014,"stage":"Series C","raised":"$100M+","last_round":"$90M Series C","last_date":"May 2020","investors":["Berkshire Partners (lead)","Crown Castle"],"desc":"Kinetic Edge for edge data centers. Crown Castle tower base deployments.","moat":"Crown Castle = 40,000 tower deployment path. AI inference edge = natural fit.","customers":["Crown Castle","Verizon edge apps"],"trl":8,"mp":13,"tm":13,"cr":12,"sr":9,"kf":10,"ep":8,"score":65,"korea":["SK Telecom","KT","LG Uplus","Samsung Networks"],"acquirer":["Crown Castle","American Tower","Verizon"],"thesis":"Edge AI inference = edge DC demand. Crown Castle = 40K site path.","risk":"Edge AI not monetized at scale. Crown Castle dependency.","url":"https://www.vapor.io"},

{"id":"jetcool","sector":"Cooling & Power Semi","sub":"Direct-to-Chip","name":"Jetcool Technologies","country":"USA","founded":2019,"stage":"Acquired (Flex)","raised":"$28.7M","last_round":"Acquired by Flex","last_date":"Nov 2024","investors":["Bosch Ventures (lead)","In-Q-Tel","Raptor Group","Schooner Capital"],"desc":"Microjet direct-to-chip liquid cooling. 1000W/cm² heat flux.","moat":"Microjet impingement. 1000W TDP solution. No server redesign.","customers":["Defense contractors","AI DC pilots"],"trl":7,"mp":14,"tm":15,"cr":10,"sr":10,"kf":11,"ep":9,"score":69,"korea":["Samsung Electronics","SK Hynix","LIG Nex1"],"acquirer":["Vertiv","Asetek","Nidec"],"thesis":"1000W GPU TDP inevitable. Direct-to-chip = highest performance.","risk":"Asetek, Vertiv competition. OEM adoption needed.","url":"https://www.jetcool.com"},

{"id":"transphorm","sector":"Cooling & Power Semi","sub":"GaN Power IC","name":"Transphorm","country":"USA","founded":2007,"stage":"Public (NASDAQ: TPVG)","raised":"Public","last_round":"SPAC 2023","last_date":"Oct 2024","investors":["KKR","Yaskawa","Google Ventures"],"desc":"GaN power ICs for AI server PSU. 99%+ efficiency. High-voltage specialist.","moat":"650V GaN = high power AI PSU. Delta Electronics partnership.","customers":["Delta Electronics","Bel Fuse","AI ODMs"],"trl":9,"mp":14,"tm":15,"cr":12,"sr":9,"kf":12,"ep":8,"score":70,"korea":["Samsung Electronics","LG Electronics","Hyundai Motor","SK On"],"acquirer":["Infineon","ON Semi","Renesas"],"thesis":"AI DC PSU efficiency = Transphorm market. Google Ventures validates.","risk":"Navitas GaN competition. TSMC dependency.","url":"https://www.transphorm.com"},

{"id":"dandelion","sector":"Cooling & Power Semi","sub":"Geothermal Cooling","name":"Dandelion Energy","country":"USA","founded":2017,"stage":"Series C","raised":"$80M","last_round":"$50M Series C","last_date":"Oct 2024","investors":["GV (Google Ventures)","EIP","Lennar"],"desc":"Residential geothermal heat pumps. Ground-source heating and cooling.","moat":"50% install cost reduction via proprietary drilling. Lennar homebuilder channel.","customers":["New York homeowners","Lennar"],"trl":9,"mp":12,"tm":13,"cr":13,"sr":8,"kf":9,"ep":8,"score":63,"korea":["LG Electronics (heat pump)","Samsung HVAC"],"acquirer":["Carrier","Trane","Johnson Controls"],"thesis":"Geothermal = free H&C. Google Ventures = AI DC cooling extension potential.","risk":"Geology dependent. Residential focus = small per-unit TAM.","url":"https://dandelionenergy.com"},

{"id":"phononic","sector":"Cooling & Power Semi","sub":"Solid-State Cooling","name":"Phononic","country":"USA","founded":2009,"stage":"Series E","raised":"$100M","last_round":"$40M Series E","last_date":"2022","investors":["Quanta Capital","Eastman Chemical","Alphabet"],"desc":"Solid-state thermoelectric cooling. No moving parts. Zero refrigerant.","moat":"Peltier modules. Silent. No F-gas = EU regulation winner.","customers":["Healthcare","Telecom equipment cooling"],"trl":8,"mp":11,"tm":13,"cr":11,"sr":10,"kf":11,"ep":7,"score":63,"korea":["Samsung Electronics","LG Electronics","SK Hynix"],"acquirer":["Alphabet","Vertiv","Nidec"],"thesis":"EU F-gas regulation + no refrigerant = winner. AI chip thermal.","risk":"Higher cost. Lower efficiency at scale vs conventional.","url":"https://phononic.com"},

{"id":"exodigo-cool","sector":"Cooling & Power Semi","sub":"AI Manufacturing","name":"Machina Labs","country":"USA","founded":2019,"stage":"Series B","raised":"$32M","last_round":"$17M Series B","last_date":"Oct 2024","investors":["Sequoia Capital","DCVC","Lockheed Martin"],"desc":"AI robotic sheet metal forming. 1/100th tooling cost. 1-day lead time.","moat":"Roboforming = robot arms replace metal dies. Defense + energy OEM manufacturing.","customers":["US Air Force","Space companies"],"trl":7,"mp":11,"tm":15,"cr":10,"sr":10,"kf":9,"ep":8,"score":63,"korea":["POSCO","Hyundai Steel","LIG Nex1"],"acquirer":["Lockheed Martin","Northrop","Boeing"],"thesis":"AI manufacturing for grid equipment production speed-up.","risk":"Defense focus initially. Energy manufacturing secondary.","url":"https://machinalabs.ai"},

{"id":"infineon","sector":"Cooling & Power Semi","sub":"SiC Power Semi","name":"Infineon Technologies","country":"Germany","founded":1999,"stage":"Public (XETRA: IFX)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["Public markets"],"desc":"SiC, GaN, Si power semiconductors. #1 market share automotive SiC.","moat":"CoolSiC. #1 global market share EV SiC. 650V-1700V range.","customers":["Tesla","BYD","VW","AI DC ODMs"],"trl":10,"mp":15,"tm":16,"cr":17,"sr":7,"kf":13,"ep":5,"score":66,"korea":["Samsung Electronics","Hyundai Motor","LG Electronics","SK On"],"acquirer":["Not acquirable at scale"],"thesis":"SiC supercycle: EV + AI DC grid inverter. #1 share = pricing power.","risk":"EV slowdown. STMicro, Onsemi competition.","url":"https://www.infineon.com"},

{"id":"on-semi","sector":"Cooling & Power Semi","sub":"SiC Power Semi","name":"onsemi","country":"USA","founded":1999,"stage":"Public (NASDAQ: ON)","raised":"Public","last_round":"Public","last_date":"N/A","investors":["Public markets"],"desc":"SiC power semiconductors for EV and industrial. EliteSiC vertically integrated.","moat":"Full vertical integration Czech Republic. BMW/VW/BYD relationships.","customers":["BMW","VW","BYD","Hyundai/Kia"],"trl":10,"mp":14,"tm":15,"cr":16,"sr":8,"kf":13,"ep":5,"score":66,"korea":["Hyundai Motor","Kia","Samsung Electronics","LG"],"acquirer":["Not acquirable"],"thesis":"EV + grid = structural SiC demand. Hyundai/Kia = Korea angle.","risk":"EV slowdown. Infineon, STMicro.","url":"https://www.onsemi.com"},



{"id":"gravity-semi","sector":"Cooling & Power Semi","sub":"Power Management IC","name":"Eta Compute","country":"USA","founded":2015,"stage":"Series B","raised":"$30M","last_round":"$16M Series B-EXT","last_date":"Nov 2023","investors":["Intel Capital","Applied Ventures","Advantage Capital"],"desc":"Ultra-low power AI edge inference chips. Energy-efficient ML inference.","moat":"Continuous dynamic voltage scaling. 10x lower power than standard edge AI.","customers":["IoT manufacturers","Industrial AI"],"trl":8,"mp":12,"tm":14,"cr":11,"sr":9,"kf":10,"ep":8,"score":64,"korea":["Samsung Electronics","LG Electronics","Hyundai"],"acquirer":["Intel","Qualcomm","Nordic Semi"],"thesis":"AI everywhere = power efficiency critical. Edge AI inference at 1/10th power.","risk":"Arm Cortex-M competition. Niche market initially.","url":"https://etacompute.com"},

{"id":"natural-power","sector":"Cooling & Power Semi","sub":"Renewable O&M","name":"Natural Power","country":"UK","founded":1994,"stage":"ERM subsidiary","raised":"ERM subsidiary","last_round":"ERM acquisition","last_date":"2020","investors":["ERM Group (parent)"],"desc":"Renewable energy O&M and advisory. 30yr wind expertise. 20GW+ advisory.","moat":"30 years wind resource data. Drone inspection. Global presence.","customers":["Major renewable IPPs globally"],"trl":10,"mp":12,"tm":12,"cr":14,"sr":6,"kf":9,"ep":7,"score":60,"korea":["SK E&S","Korea Midland Power","KOSEP"],"acquirer":["WSP","AECOM","Wood Group"],"thesis":"AI DC renewable asset O&M = data-driven performance optimization.","risk":"ERM integration. Professional services margin.","url":"https://www.naturalpower.com"},

{"id":"enchanted-cool","sector":"Cooling & Power Semi","sub":"Two-Phase Cooling","name":"Zutacore","country":"Israel/USA","founded":2016,"stage":"Seed+","raised":"~$11M","last_round":"Carrier Ventures investment","last_date":"Feb 2025","investors":["Samsung Ventures","Carrier Ventures","Wiwynn","MHI (Mitsubishi Heavy Industries)","SoftBank"],"desc":"Two-phase direct-to-chip liquid cooling. Dielectric fluid evaporation at chip surface.","moat":"Phase change = 1000W+ TDP capable. No pump required. Samsung Next validation.","customers":["Intel (internal)","AI DC pilots"],"trl":7,"mp":15,"tm":15,"cr":10,"sr":10,"kf":13,"ep":9,"score":72,"korea":["Samsung Electronics","SK Hynix","LG Electronics"],"acquirer":["Intel (existing)","Vertiv","Schneider"],"thesis":"Two-phase = highest cooling density. Samsung + Intel = credibility for AI DC.","risk":"Complex coolant management. Retrofit difficulty.","url":"https://zutacore.com"},

{"id":"bloom-cool","sector":"Cooling & Power Semi","sub":"Immersion Cooling Market","name":"Asperitas","country":"Netherlands","founded":2015,"stage":"Series B","raised":"$25M","last_round":"$15M Series B","last_date":"Oct 2024","investors":["Invest-NL","ABN AMRO Ventures"],"desc":"Natural convection immersion cooling. No pumps. Passive liquid immersion.","moat":"Passive = no pump failure risk. Open architecture. EU data center focus.","customers":["European HPC","Dutch universities"],"trl":8,"mp":13,"tm":13,"cr":11,"sr":9,"kf":9,"ep":7,"score":63,"korea":["Samsung Electronics","SK Hynix"],"acquirer":["Schneider","Vertiv","ABB"],"thesis":"EU DC efficiency regulations + passive immersion = regulatory play.","risk":"Iceotope, Submer competition. North America expansion needed.","url":"https://asperitas.com"},

{"id":"liqid-tech","sector":"Cooling & Power Semi","sub":"Composable Infrastructure","name":"Liqid","country":"USA","founded":2014,"stage":"Series C","raised":"$100M","last_round":"$50M Series C","last_date":"Oct 2024","investors":["Koch Industries","Hewlett Packard Pathfinder","Samsung Ventures"],"desc":"Composable disaggregated infrastructure for AI DC. Dynamic GPU/CPU/memory pooling.","moat":"PCIe fabric = real-time AI workload optimization. Samsung Ventures validation.","customers":["US Air Force","Enterprise AI DC"],"trl":8,"mp":14,"tm":15,"cr":12,"sr":9,"kf":12,"ep":8,"score":70,"korea":["Samsung Electronics","SK Hynix","Naver","KT"],"acquirer":["Samsung","Intel","AMD"],"thesis":"AI workload composability = power efficiency. Dynamic allocation reduces wasted TDP.","risk":"VMware/Microsoft competition. Enterprise sales cycle long.","url":"https://liqid.com"},

]

if __name__ == "__main__":
    from collections import Counter
    print(f"Total: {len(COMPANIES)} companies")
    sectors = Counter(c['sector'] for c in COMPANIES)
    for s, n in sectors.items():
        print(f"  {s}: {n}")
    scores = [c['score'] for c in COMPANIES]
    print(f"\nScore distribution:")
    print(f"  80+  (LEAD):   {sum(1 for s in scores if s >= 80)}")
    print(f"  70-79 (FOLLOW): {sum(1 for s in scores if 70 <= s < 80)}")
    print(f"  60-69 (WATCH):  {sum(1 for s in scores if 60 <= s < 70)}")
    print(f"  <60  (PASS):   {sum(1 for s in scores if s < 60)}")

# 5개 추가 — 100개 완성
EXTRA = [
{"id":"nuscale","sector":"DC Power & BTM","sub":"SMR","name":"NuScale Power","country":"USA","founded":2007,"stage":"Public (NYSE: SMR)","raised":"Public","last_round":"SPAC 2022","last_date":"2022","investors":["Fluor","DOE $1.4B","Public markets"],"desc":"VOYGR 77MW SMR. First NRC-certified SMR design in the US.","moat":"Only NRC-certified SMR design. 12-module scalable plant.","customers":["UAMPS project cancelled 2023"],"trl":6,"mp":13,"tm":16,"cr":3,"sr":18,"kf":9,"ep":6,"score":65,"korea":["KEPCO","Doosan","KAERI"],"acquirer":["Fluor","KEPCO"],"thesis":"First NRC cert is moat. But UAMPS cancellation signals economics challenge.","risk":"$15,000/kW. No committed offtake. PASS for now.","url":"https://www.nuscalepower.com"},
{"id":"stem-grid","sector":"Grid Software","sub":"Grid Analytics","name":"AutoGrid (Enel X)","country":"USA","founded":2011,"stage":"Acquired","raised":"Acquired by Enel X 2023","last_round":"Exit to Enel X","last_date":"Oct 2024","investors":["EIP","GE Ventures","RWE"],"desc":"DERMS platform for utility VPP. 60+ utility customers globally.","moat":"Utility-grade reliability. ISO market integration. 60+ utility base.","customers":["60+ utilities globally"],"trl":9,"mp":15,"tm":14,"cr":17,"sr":6,"kf":11,"ep":10,"score":73,"korea":["KEPCO","KT","LG Uplus"],"acquirer":["Enel X (acquired)"],"thesis":"VPP/DERMS = utility standard. Enel X acquisition validates.","risk":"Post-acquisition integration risk.","url":"https://auto-grid.com"},
{"id":"fluence","sector":"ESS / LDES","sub":"BESS Integration","name":"Fluence Energy","country":"USA","founded":2018,"stage":"Public (NASDAQ: FLNC)","raised":"Public","last_round":"IPO 2021","last_date":"2021","investors":["Siemens Energy","AES Corporation","Public markets"],"desc":"Fluence IQ AI auto-bidding + 15GW+ BESS pipeline. Siemens+AES JV.","moat":"IQ software = recurring revenue moat. 15GW+ = scale. Hardware-agnostic.","customers":["Global utilities","IPPs","Hyperscalers"],"trl":9,"mp":16,"tm":15,"cr":16,"sr":7,"kf":12,"ep":8,"score":74,"korea":["Samsung SDI","LG Energy","KEPCO","SK On"],"acquirer":["Eaton","Schneider","ABB"],"thesis":"Software-defined BESS. IQ platform creates recurring revenue above hardware.","risk":"Hardware margin pressure. Samsung SDI competition.","url":"https://fluenceenergy.com"},
{"id":"vertiv-grid","sector":"Grid Equipment","sub":"Power Conversion","name":"ABB Power Electronics","country":"Switzerland","founded":1988,"stage":"ABB subsidiary","raised":"ABB subsidiary","last_round":"ABB divested Power Grids (Hitachi) 2020","last_date":"2020","investors":["ABB Group"],"desc":"UPS, frequency converters, solar inverters. AI DC power conversion.","moat":"ABB brand. Global service network. GridBeyond co-investor.","customers":["Global utilities","Data centers","Industry"],"trl":10,"mp":15,"tm":15,"cr":17,"sr":6,"kf":13,"ep":5,"score":71,"korea":["KEPCO","Samsung Electronics","HD Hyundai","LS Electric"],"acquirer":["Not acquirable"],"thesis":"ABB power electronics = AI DC UPS and inverter market. GridBeyond validates software angle.","risk":"Hitachi Energy divested. Portfolio complexity.","url":"https://www.abb.com"},
{"id":"zutacore","sector":"Cooling & Power Semi","sub":"Two-Phase Cooling","name":"LiquidStack","country":"Netherlands/USA","founded":2012,"stage":"Acquired","raised":"$45M","last_round":"Acquired by Trane Technologies","last_date":"Mar 2026","investors":["Trane Technologies","Tiger Global","Wiwynn","BitFury"],"desc":"Two-phase immersion cooling. Microsoft-backed. AI DC thermal at scale.","moat":"Microsoft validation. Two-phase = highest density. Wiwynn = ODM channel.","customers":["Microsoft (pilot)","Major ODMs"],"trl":8,"mp":16,"tm":15,"cr":13,"sr":9,"kf":12,"ep":9,"score":74,"korea":["Samsung Electronics","SK Hynix","LG CNS"],"acquirer":["Microsoft","Vertiv","Schneider"],"thesis":"Microsoft backing = highest credibility. Two-phase = next-gen AI DC cooling standard.","risk":"Complex deployment. Iceotope, Submer competition.","url":"https://liquidstack.com"},
]

COMPANIES.extend(EXTRA)
